import os

abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

features = []


def feature(name, default, min, max, pow2=None):
    vals = set()
    val = min
    while val <= max:
        vals.add(val)
        if pow2 == True or (isinstance(pow2, int) and val >= pow2):
            val *= 2
        else:
            val += 1
    vals.add(default)

    features.append(
        {
            "name": name,
            "default": default,
            "vals": sorted(list(vals)),
        }
    )


# Packet pool. Always used, with or without the `alloc` feature.
feature("packet_buf_count", default=16, min=1, max=4096, pow2=8)
feature("packet_buf_align", default=1, min=1, max=32, pow2=True)

# Interfaces and tables (only bounded without `alloc`).
feature("iface_count", default=2, min=1, max=8)
feature("iface_addr_count", default=4, min=1, max=16, pow2=8)
feature("route_count", default=4, min=0, max=64, pow2=8)
feature("multicast_group_count", default=8, min=1, max=1024, pow2=8)
feature("slaac_prefix_count", default=2, min=1, max=16, pow2=8)
feature("slaac_router_count", default=2, min=1, max=16, pow2=8)

# Always bounded.
feature("neighbor_cache_count", default=8, min=1, max=1024, pow2=8)
feature("pending_queue_count", default=16, min=1, max=256, pow2=8)

# Socket slabs (only bounded without `alloc`).
feature("udp_socket_count", default=4, min=1, max=64, pow2=8)
feature("raw_socket_count", default=2, min=1, max=64, pow2=8)
feature("tcp_socket_count", default=4, min=1, max=64, pow2=8)
feature("tcp_listener_count", default=2, min=1, max=64, pow2=8)

# Per-socket queues. Always bounded.
feature("udp_rx_queue_count", default=4, min=1, max=64, pow2=8)
feature("raw_rx_queue_count", default=4, min=1, max=64, pow2=8)
feature("tcp_listener_backlog", default=4, min=1, max=64, pow2=8)
feature("assembler_max_segment_count", default=4, min=1, max=32, pow2=4)

# IPv4 and 6LoWPAN reassembly (features `ipv4-reassembly`,
# `sixlowpan-reassembly`): datagrams reassembled at once.
feature("reassembly_buffer_count", default=1, min=1, max=32, pow2=4)

# 6LoWPAN address contexts per interface (feature `medium-ieee802154`). The
# context identifier is 4 bits, so 16 is the most a packet can name.
feature("sixlowpan_address_context_count", default=4, min=1, max=16)

# DNS and DHCP.
feature("dns_max_query_count", default=4, min=1, max=32, pow2=4)
feature("dns_max_result_count", default=4, min=1, max=32, pow2=4)
feature("dns_max_server_count", default=4, min=1, max=32, pow2=4)
feature("dns_max_name_size", default=255, min=64, max=255, pow2=True)
feature("dhcp_max_dns_server_count", default=3, min=1, max=8)
feature("dhcp_options_buf_size", default=128, min=16, max=1024, pow2=True)

# ========= Update Cargo.toml

things = ""
for f in features:
    name = f["name"].replace("_", "-")
    for val in f["vals"]:
        things += f"{name}-{val} = []"
        if val == f["default"]:
            things += " # Default"
        things += "\n"
    things += "\n"

SEPARATOR_START = "# BEGIN AUTOGENERATED CONFIG FEATURES\n"
SEPARATOR_END = "# END AUTOGENERATED CONFIG FEATURES\n"
HELP = "# Generated by gen_config.py. DO NOT EDIT.\n"
with open("Cargo.toml", "r") as f:
    data = f.read()
before, data = data.split(SEPARATOR_START, maxsplit=1)
_, after = data.split(SEPARATOR_END, maxsplit=1)
data = before + SEPARATOR_START + HELP + things + SEPARATOR_END + after
with open("Cargo.toml", "w") as f:
    f.write(data)


# ========= Update build.rs

things = ""
for f in features:
    name = f["name"].upper()
    things += f'    ("{name}", {f["default"]}),\n'

SEPARATOR_START = "// BEGIN AUTOGENERATED CONFIG FEATURES\n"
SEPARATOR_END = "// END AUTOGENERATED CONFIG FEATURES\n"
HELP = "    // Generated by gen_config.py. DO NOT EDIT.\n"
with open("build.rs", "r") as f:
    data = f.read()
before, data = data.split(SEPARATOR_START, maxsplit=1)
_, after = data.split(SEPARATOR_END, maxsplit=1)
data = before + SEPARATOR_START + HELP + things + "    " + SEPARATOR_END + after
with open("build.rs", "w") as f:
    f.write(data)
