#![cfg_attr(not(any(test, feature = "std")), no_std)]
#![doc = include_str!("../README.md")]
//!
//! ## Feature flags
#![doc = document_features::document_features!(feature_label = r#"<span class="stab portability"><code>{feature}</code></span>"#)]

#[cfg(any(feature = "alloc", test))]
extern crate alloc;

// So that `src/test_device.rs` can name this crate as `xarxa` both here and in the
// integration tests that `#[path]`-include it.
#[cfg(test)]
extern crate self as xarxa;

#[cfg(not(any(feature = "medium-ethernet", feature = "medium-ip", feature = "medium-ieee802154")))]
compile_error!("You must enable at least one of the following features: medium-ethernet, medium-ip, medium-ieee802154");

#[cfg(all(
    feature = "slaac",
    not(any(feature = "medium-ethernet", feature = "medium-ieee802154"))
))]
compile_error!("The slaac feature needs medium-ethernet or medium-ieee802154.");

#[cfg(not(any(feature = "ipv4", feature = "ipv6")))]
compile_error!("You must enable at least one of the following features: ipv4, ipv6");

#[cfg(all(feature = "tcp-reno", feature = "tcp-cubic"))]
compile_error!("The features tcp-reno and tcp-cubic are mutually exclusive.");

// Must go first so other modules see its macros.
#[macro_use]
mod fmt;

#[macro_use]
mod macros;

/// Compile-time size knobs, generated by `build.rs` from the `<knob>-<N>` cargo
/// features and the `XARXA_<KNOB>` environment variables.
mod config {
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/config.rs"));
}

pub mod buf;
#[cfg(feature = "dhcpv4")]
pub mod dhcpv4;
#[cfg(feature = "dns")]
pub mod dns;
#[cfg(feature = "std")]
pub mod driver_impls;
#[cfg(any(feature = "ipv4-fragmentation", feature = "sixlowpan-fragmentation"))]
mod fragmentation;
#[cfg(feature = "icmp-errors")]
mod icmp_error;
pub mod meta;
#[cfg(feature = "multicast")]
pub mod multicast;
#[cfg(any(feature = "medium-ethernet", feature = "medium-ieee802154"))]
pub mod neighbor;
#[cfg(feature = "packet-log")]
mod packet_log;
mod rand;
#[cfg(feature = "raw")]
pub mod raw;
#[cfg(any(feature = "ipv4-reassembly", feature = "sixlowpan-reassembly"))]
mod reassembly;
pub mod route;
#[cfg(feature = "medium-ieee802154")]
mod sixlowpan;
#[cfg(feature = "slaac")]
pub mod slaac;
pub mod stack;
mod storage;
#[cfg(feature = "tcp")]
pub mod tcp;
#[cfg(test)]
mod test_device;
pub mod time;
#[cfg(feature = "udp")]
pub mod udp;
#[cfg(feature = "async")]
mod waker;
pub mod wire;

/// The driver interface, re-exported for driver crates and code that names their types.
pub use xarxa_driver as driver;

pub use buf::{PACKET_BUF_SIZE, PacketBuf};
#[cfg(feature = "dhcpv4-options")]
pub use dhcpv4::DhcpLeaseOptions;
#[cfg(feature = "dhcpv4")]
pub use dhcpv4::{DhcpConfig, DhcpLease, DhcpServerInfo};
#[cfg(feature = "dns")]
pub use dns::{DnsClient, DnsQueryHandle};
#[cfg(feature = "icmp-errors")]
pub use icmp_error::IcmpError;
pub use meta::PacketMeta;
#[cfg(feature = "packetmeta-timestamp")]
pub use meta::{Timestamp, TxTimestamp};
#[cfg(feature = "multicast")]
pub use multicast::MulticastError;
#[cfg(feature = "raw")]
pub use raw::{RawHandle, RawMode, RawSocket};
pub use route::{Route, RouteOrigin, Routes};
#[cfg(feature = "slaac")]
pub use slaac::{SlaacConfig, SlaacState};
#[cfg(feature = "raw")]
pub use stack::RawSocketIter;
#[cfg(feature = "tcp-listener")]
pub use stack::TcpListenerIter;
#[cfg(feature = "tcp")]
pub use stack::TcpSocketIter;
#[cfg(feature = "udp")]
pub use stack::UdpSocketIter;
pub use stack::{AddrOrigin, Iface, IfaceAddr, IfaceHandle, IfaceIter, Medium, Stack};
pub use storage::Full;
#[cfg(feature = "tcp")]
pub use tcp::{TcpHandle, TcpSocket};
#[cfg(feature = "tcp-listener")]
pub use tcp::{TcpListener, TcpListenerHandle};
#[cfg(feature = "udp")]
pub use udp::{UdpHandle, UdpSocket};
